force-app/main/default/objects/Customer_Portal_Notification__c/Customer_Portal_Notification__c.object-meta.xml
<CustomObject>
    <label>Customer Portal Notification</label>
    <nameField>
        <displayFormat>CPN-{0000}</displayFormat>
        <label>Customer Portal Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Portal Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Portal_Notification__c/fields/Created_For_CC__c.field-meta.xml
<CustomField>
    <fullName>Created_For_CC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created For CC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Portal_Notification__c/fields/IsNotificationSent__c.field-meta.xml
<CustomField>
    <fullName>IsNotificationSent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Notification Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Portal_Notification__c/fields/Updated_Status__c.field-meta.xml
<CustomField>
    <fullName>Updated_Status__c</fullName>
    <label>Updated Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerPortalNotificationTriggerHandler.cls
public without sharing class CustomerPortalNotificationTriggerHandler {

    public static void handleAfterInsert(List<Customer_Portal_Notification__c> newList) {
        List<Id> notificationIds = new List<Id>();
        for (Customer_Portal_Notification__c noti : newList) {
            if (noti.IsActive__c == true && noti.IsNotificationSent__c == false && noti.Created_For_CC__c == true) {
                notificationIds.add(noti.Id);
            }
        }
        sendNotifications(notificationIds);
    }

    public static void handleAfterUpdate(List<Customer_Portal_Notification__c> newList, Map<Id, Customer_Portal_Notification__c> oldMap) {
        List<Id> notificationIds = new List<Id>();
        for (Customer_Portal_Notification__c noti : newList) {
            Customer_Portal_Notification__c oldNoti = oldMap.get(noti.Id);
            if (noti.IsActive__c == true && oldNoti.Updated_Status__c != noti.Updated_Status__c) {
                notificationIds.add(noti.Id);
            }
        }
        sendNotifications(notificationIds);
    }

    private static void sendNotifications(List<Id> notificationIds) {
        for (Id notiId : notificationIds) {
            CPSendNotificationController.sendNotification(String.valueOf(notiId));
        }
    }
}