force-app/main/default/objects/Apex_Log__c/Apex_Log__c.object-meta.xml
<CustomObject>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>APLG-{0000}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Customer_Master__c.field-meta.xml
<CustomField>
    <fullName>Customer_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Master</label>
    <referenceTo>Customer_Master__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Quote__r.GRAND_TOTAL__c /*Total_Cost_of_the_Flat__c + GST_5__c*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>GRAND_TOTAL__c+ Total_Interest__c - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending_Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Son_Daughter_Wife_of__c.field-meta.xml
<CustomField>
    <fullName>Son_Daughter_Wife_of__c</fullName>
    <label>S/o,D/o,W/o</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S/o</fullName>
            </value>
            <value>
                <fullName>D/o</fullName>
            </value>
            <value>
                <fullName>W/o</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_received_Amount__c</fullName>
    <label>Total_received_Amount</label>
    <summarizedField>Receipt__c.Total_Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Approval_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Payment_Type__c</field>
        <operation>notEqual</operation>
        <value>Additional Charges</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co Applicant</label>
    <nameField>
        <label>Co Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Co Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Applicant__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Master__c/Customer_Master__c.object-meta.xml
<CustomObject>
    <label>Customer Master</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Customer Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Portal_Notification_Subscriber__c/Customer_Portal_Notification_Subscriber__c.object-meta.xml
<CustomObject>
    <label>Customer Portal Notification Subscriber</label>
    <nameField>
        <displayFormat>CPNS-{0000}</displayFormat>
        <label>Customer Portal Notification Subscriber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Portal Notification Subscribers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Portal_Notification_Subscriber__c/fields/Customer_Master__c.field-meta.xml
<CustomField>
    <fullName>Customer_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Master</label>
    <referenceTo>Customer_Master__c</referenceTo>
    <relationshipLabel>Customer Portal Notification Subscribers</relationshipLabel>
    <relationshipName>Customer_Portal_Notification_Subscribers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Query__c/Customer_Query__c.object-meta.xml
<CustomObject>
    <label>Customer Query</label>
    <nameField>
        <displayFormat>CQ-{0000}</displayFormat>
        <label>Customer Query Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Query</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Query__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Customer Query</relationshipLabel>
    <relationshipName>Customer_Query</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Query__c/fields/Customer_Master__c.field-meta.xml
<CustomField>
    <fullName>Customer_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Master</label>
    <referenceTo>Customer_Master__c</referenceTo>
    <relationshipLabel>Customer Query</relationshipLabel>
    <relationshipName>Customer_Query</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/Demand_Raised__c.object-meta.xml
<CustomObject>
    <label>Demand Raised</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>Demand Raised Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Raised</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand_Raised__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Parent_Demand__c.field-meta.xml
<CustomField>
    <fullName>Parent_Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Demand</label>
    <referenceTo>Demand_Raised__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment schedule</label>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Booking__r.Project1__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <formula>IF(
  Is_Clubhouse_Charges__c, Booking__r.Clubhouse_Charges__c,
  IF(Is_Infrastructure_Charges__c, Booking__r.Total_Infrastructure_Charges__c,
    IF(Is_Maintenance_Charges__c, Booking__r.Total_Maintenance_Amount__c,
      IF(
        Booking__r.RecordType.DeveloperName &lt;&gt; &apos;Plots&apos;,
        Payment_percent__c * Quote__r.GRAND_TOTAL__c,
										(Booking__r.Agreement_Value__c - Booking__r.Total_Infrastructure_Charges__c) * Payment_percent__c)))
     
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Payment_percent__c.field-meta.xml
<CustomField>
    <fullName>Payment_percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment percent</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Payable_Amount__c   - Received_Amount1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Received_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount1__c</fullName>
    <label>Received_Amount</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status_Picklist__c</field>
        <operation>notEqual</operation>
        <value>Rejected</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Demanded</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>Ref-{0000}</displayFormat>
        <label>Refferal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Customer_Master__c.field-meta.xml
<CustomField>
    <fullName>Customer_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Master</label>
    <referenceTo>Customer_Master__c</referenceTo>
    <relationshipLabel>Referral</relationshipLabel>
    <relationshipName>Referral</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Rewarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomeScreen_CCMobileAPI.cls
/**
 * @description REST API endpoint for Contact Center mobile application home screen.
 * Validates customer and booking, then retrieves comprehensive booking details including
 * property info, payment status, co-applicants, demands, payments, documents, and milestones.
 *
 * Request:
 * {
 *   "userId": "CPC0023",
 *   "bookingId": "CCP005"
 * }
 *
 * @author Praveen Kumar
 * @version 1.0
 * @since 2026-02-18
 */
@RestResource(urlMapping='/CCHomeScreenAPI/*')
global without sharing class HomeScreen_CCMobileAPI {

    /**
     * @description Handles POST requests to retrieve home screen data for a booking.
     * Validates userId and bookingId, verifies booking belongs to customer,
     * and retrieves all associated booking details.
     * All requests and responses are logged to Apex_Log__c for audit trail.
     */
    @HttpPost
    global static void getHomeScreenData() {
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString();

        Apex_Log__c log = new Apex_Log__c();
        log.Request_Type__c = 'HomeScreen_CCMobileAPI';
        log.Request__c = requestBody;

        try {
            HomeScreenRequestWrapper requestData = (HomeScreenRequestWrapper) JSON.deserialize(requestBody, HomeScreenRequestWrapper.class);

            String userId = requestData.userId;
            String bookingId = requestData.bookingId;

            // Validate that required fields are not empty
            if (String.isBlank(userId) || String.isBlank(bookingId)) {
                ErrorResponseUitilityClass.sendErrorResponse('Please provide userId and bookingId', 'HomeScreen_CCMobileAPI', requestBody);
                return;
            }

            // Query customer by userId (Name or Id)
            List<Customer_Master__c> cmList = [
                SELECT Id, Name
                FROM Customer_Master__c
                WHERE (Id = :userId OR Name = :userId)
                AND Active__c = True
                LIMIT 1
            ];

            if (cmList.isEmpty()) {
                ErrorResponseUitilityClass.sendErrorResponse('Customer Not Found', 'HomeScreen_CCMobileAPI', requestBody);
                return;
            }

            Customer_Master__c customer = cmList[0];

            // Query Booking with related details
            List<Booking__c> bookingList = [
                SELECT Id, Name, Customer_Master__c, Plot__c, Plot__r.Name, Plot__r.Project__c, Plot__r.Project__r.Name, Plot__r.Project__r.Project_Address__c,
                       Plot__r.BHK_Type__c, Plot__r.Carpet_Area__c, 
                       GRAND_TOTAL__c, Total_received_Amount__c,
                        (SELECT Id FROM Demand_Raised__r),
                       (SELECT Id FROM Receipts__r),
                       (SELECT Id FROM Co_Applicants__r),
                       (SELECT Id FROM Payment_schedules__r)
                FROM Booking__c
                WHERE Name = :bookingId AND Customer_Master__c =:customer.Id
                LIMIT 1
            ];

            if (bookingList.isEmpty()) {
                ErrorResponseUitilityClass.sendErrorResponse('Booking Not Found', 'HomeScreen_CCMobileAPI', requestBody);
                return;
            }

            Booking__c booking = bookingList[0];

            // Verify booking belongs to the customer
            if (booking.Customer_Master__c != customer.Id) {
                ErrorResponseUitilityClass.sendErrorResponse('Booking does not belong to this customer', 'HomeScreen_CCMobileAPI', requestBody);
                return;
            }

            // Query Unit/Plot details
            List<Plot__c> plotList = [
                SELECT Id, Name, BHK_Type__c, Carpet_Area__c,  Project__r.Name, Project__r.Project_Address__c,Unit_Facing_Direction__c,Super_Built_up_Area__c
                FROM Plot__c
                WHERE Id = :booking.Plot__c
                LIMIT 1
            ];

            Plot__c plot = plotList.isEmpty() ? null : plotList[0];

            // Query Demands for this booking
            Integer demandCount = booking.Demand_Raised__r != null ? booking.Demand_Raised__r.size() : 0;
            Integer propertyCount = [SELECT COUNT() FROM Booking__c WHERE Customer_Master__c = :customer.Id];

            // Query Payments for this booking
            Integer paymentCount = booking.Receipts__r != null ? booking.Receipts__r.size() : 0;

            // Query Co-Applicants
            List<Co_Applicant__c> coApplicants = [
                SELECT Id, Name, Son_Daughter_Wife_of__c, Aadhar_Number__c, PAN_Number__c
                FROM Co_Applicant__c
                WHERE Booking__c = :booking.Id
            ];

            // Query Project Milestones
            List<Payment_schedule__c> projectMilestones = [
                SELECT Id, Name, Last_Payment_Date__c, Payment_percent__c, Amount__c, AmountB__c,
                       Received_Amount1__c, Pending_Amount__c, Status__c
                FROM Payment_schedule__c
                WHERE Booking__c = :booking.Id
                ORDER BY S_No__c ASC
            ];

            // Query Customer Queries related to Booking
            Integer queryCount = [SELECT COUNT() FROM Customer_Query__c WHERE Booking__c = :booking.Id];

            // Build property detail
            PropertyDetail propertyDetail = new PropertyDetail();
            propertyDetail.propertyName = plot != null && plot.Name != null ? plot.Name+' '+Plot.Project__r.Name : ' ';
            propertyDetail.propertyUnit = plot != null && plot.Name != null ? plot.Name : ' ';
            propertyDetail.bhk = plot != null && plot.BHK_Type__c != null ? plot.BHK_Type__c : ' ';
            propertyDetail.propertySqft = plot != null && plot.Super_Built_up_Area__c != null ? String.valueOf(plot.Super_Built_up_Area__c) + ' sq.ft' : '';
            propertyDetail.propertyFacing = plot != null && plot.Unit_Facing_Direction__c != null ? plot.Unit_Facing_Direction__c : '';

            // Build co-applicants list
            List<CoApplicantDetail> coApplicantsList = new List<CoApplicantDetail>();
            for (Co_Applicant__c coApp : coApplicants) {
                CoApplicantDetail coAppDetail = new CoApplicantDetail();
                coAppDetail.coApplicantName = coApp.Name != null ? coApp.Name : '';
                coAppDetail.coApplicantCareOf = coApp.Son_Daughter_Wife_of__c != null ? coApp.Son_Daughter_Wife_of__c : '';
                coAppDetail.coApplicantAadharNumber = coApp.Aadhar_Number__c != null ? coApp.Aadhar_Number__c : '';
                coAppDetail.coApplicantPANNumber = coApp.PAN_Number__c != null ? coApp.PAN_Number__c : '';
                coApplicantsList.add(coAppDetail);
            }

            // Build project milestones list
            List<MilestoneDetail> milestonesList = new List<MilestoneDetail>();
            Decimal totalMilestonePaymentPercentage = 0;
            for (Payment_schedule__c milestone : projectMilestones) {
                MilestoneDetail milestoneDetail = new MilestoneDetail();
                milestoneDetail.milestoneName = milestone.Name != null ? milestone.Name : '';
                milestoneDetail.milestoneDate = formatDateAsIsoUtc(milestone.Last_Payment_Date__c);
                milestoneDetail.milestonePaymentPercentage = milestone.Payment_percent__c != null ? milestone.Payment_percent__c.intValue() : 0;
                if (milestone.Payment_percent__c != null && milestone.Status__c != null && milestone.Status__c.trim().toLowerCase() == 'completed') {
                    totalMilestonePaymentPercentage += milestone.Payment_percent__c;
                }
                //milestoneDetail.milestoneAmount = formatAmountInLakhs(milestone.Amount__c);
                 milestoneDetail.milestoneAmount = String.Valueof(milestone.AmountB__c);
             milestoneDetail.milestonePaidAmount = String.Valueof(milestone.Received_Amount1__c);
                milestoneDetail.milestonePendingAmount = String.Valueof(milestone.Pending_Amount__c);
                milestoneDetail.milestoneStatus = milestone.Status__c != null ? milestone.Status__c : '';
                milestonesList.add(milestoneDetail);
            }

            // Calculate payment percentage and amounts
            Decimal totalAmount = booking.GRAND_TOTAL__c != null ? booking.GRAND_TOTAL__c : 0;
            Decimal paidAmount = booking.Total_received_Amount__c != null ? booking.Total_received_Amount__c : 0;
            Decimal balanceAmount = totalAmount - paidAmount;
            Decimal paymentPercentage = totalMilestonePaymentPercentage;

            //For new Launch Project Image
            List<Project__c> projects = [ SELECT Id, Name FROM Project__c   WHERE Active__c = TRUE   AND New_Launch__c = TRUE];
               Boolean unReadNotificationExists = [SELECT COUNT() FROM Customer_Portal_Notification_Subscriber__c WHERE Customer_Master__c = :cmList[0].Id AND isRead__c = FALSE] > 0;

            Set<Id> projectIds = new Set<Id>();
            Map<Id, String> projectIdToName = new Map<Id, String>();
            
            for (Project__c p : projects) {
                projectIds.add(p.Id);
                projectIdToName.put(p.Id, p.Name);
            }
            
            Map<Id, Id> contentDocToProject = new Map<Id, Id>();
            if (!projectIds.isEmpty()) {
                List<ContentDocumentLink> cdlst =[SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink  WHERE LinkedEntityId IN :projectIds];
                System.debug(cdlst);
                for (ContentDocumentLink cdl : cdlst) {
                    contentDocToProject.put(cdl.ContentDocumentId, cdl.LinkedEntityId);
                }
            }
            
            Map<Id, ContentVersion> docToVersion = new Map<Id, ContentVersion>();
            List<ContentVersion> cvlist =[SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE IsLatest = TRUE AND ContentDocumentId IN :contentDocToProject.keySet() ];
            System.debug(cvlist);
            for (ContentVersion cv : cvlist) {
                if (cv.Title != null && cv.Title.contains('New Launch')) {
                    //docToVersion.put(cv.Id, cv);
                    docToVersion.put(cv.ContentDocumentId, cv);
                    
                }
            }
            Map<Id, String> projectIdToImageUrl = new Map<Id, String>();
              Map<Id, List<String>> projectIdToImageUrls = new Map<Id, List<String>>();
            
            // List<ContentDistribution> cdlsy =[select id,DistributionPublicUrl,ContentDownloadUrl,ContentVersion.Title,ContentVersion.FileExtension,createdDate from ContentDistribution where ContentVersionId IN :docToVersion.keySet() ORDER BY CREATEDDATE DESC ];
            
            
            List<ContentDistribution> cdlsy = [ SELECT ContentVersionId, ContentDownloadUrl  FROM ContentDistribution  WHERE ContentVersionId IN :docToVersion.values()   ORDER BY CreatedDate DESC];
            System.debug(cdlsy);
            for (ContentDistribution cd : cdlsy) {
            Id contentDocumentId;
                
                for (ContentVersion cv : docToVersion.values()) {
                    if (cv.Id == cd.ContentVersionId) {
                        contentDocumentId = cv.ContentDocumentId;
                        break;
                    }
                }
                
                if (contentDocumentId == null) continue;
                
                Id projectId = contentDocToProject.get(contentDocumentId);
                if (projectId == null) continue;
                
            String imgUrl = cd.ContentDownloadUrl
                .replace('download/?', 'renditionDownload?rendition=ORIGINAL_Jpg&')
                .replace('&ids', '&versionId');

            if (!projectIdToImageUrls.containsKey(projectId)) {
                projectIdToImageUrls.put(projectId, new List<String>());
            }
            projectIdToImageUrls.get(projectId).add(imgUrl);
        }
 


            // Build home screen data
            // Get actual document count for this booking
            Integer documentCount = 0;
            List<ContentDocumentLink> bookingDocLinks = [
                SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :booking.Id
            ];
            if (!bookingDocLinks.isEmpty()) {
                Set<Id> bookingDocIds = new Set<Id>();
                for (ContentDocumentLink cdl : bookingDocLinks) {
                    bookingDocIds.add(cdl.ContentDocumentId);
                }
                documentCount = [SELECT COUNT() FROM ContentVersion WHERE ContentDocumentId IN :bookingDocIds AND IsLatest = true];
            }

            HomeScreenData homeScreenData = new HomeScreenData();
            homeScreenData.percentagePaymentDone = paymentPercentage;
            homeScreenData.paidAmount = formatAmountInLakhs(paidAmount);
            homeScreenData.balanceAmount = formatAmountInLakhs(balanceAmount);
            homeScreenData.propertyDetail = propertyDetail;
            homeScreenData.newLaunch = new List<NewLaunch>(); // Static for now
            homeScreenData.unReadNotification = unReadNotificationExists;
            homeScreenData.demandCount = demandCount;
            homeScreenData.propertyCount = propertyCount;
            homeScreenData.payments = paymentCount;
            homeScreenData.documents = documentCount;
            homeScreenData.raiseQuery = queryCount;
            homeScreenData.referrals = [SELECT COUNT() FROM Referral__c WHERE Customer_Master__c = :customer.Id];
            homeScreenData.coApplicantsDetails = coApplicantsList;
            homeScreenData.projectMilestones = milestonesList;

            // Build response
            HomeScreenResponse response = new HomeScreenResponse();
            response.status = true;
            response.message = 'Basic Data';
            response.data = homeScreenData;
            /*
             for (Id pid : projectIdToName.keySet()) {
                if (projectIdToImageUrl.containsKey(pid)) {
                    response.data.newLaunch.add(
                        new NewLaunch(
                            projectIdToImageUrl.get(pid),
                            projectIdToName.get(pid)
                        )
                    );
                }
            }*/
            for (Id pid : projectIdToImageUrls.keySet()) {
            for (String url : projectIdToImageUrls.get(pid)) {
                response.data.newLaunch.add(
                    new NewLaunch(url, projectIdToName.get(pid))
                );
            }
        }
          

            RestContext.response.statusCode = 200;
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(response));

            log.Response__c = 'Home screen data retrieved for booking ' + booking.Name + ' - ' + JSON.serialize(response.data);
            log.Status__c = 'SUCCESS';
            insert log;

        } catch (Exception e) {
            ErrorResponseUitilityClass.sendErrorResponse(e.getStackTraceString() + ' - ' + e.getMessage(), 'HomeScreen_CCMobileAPI', requestBody);
        }
    }

    // ===== Request Wrapper =====
    public class HomeScreenRequestWrapper {
        public String userId;    // Customer identifier
        public String bookingId; // Booking identifier
    }

    // ===== Response Data Wrappers =====
    public class PropertyDetail {
        public String propertyName;      // Property/Project name
        public String propertyUnit;      // Unit/Plot number
        public String propertySqft;      // Property area in sq.ft
        public String propertyFacing;    // Property area in sq.ft
        public String bhk;    // Property facing direction
    }

    public class NewLaunch {
        public String siteImage;
        public String siteName;
        public NewLaunch(String siteImage, String siteName) {
            this.siteImage = siteImage;
            this.siteName = siteName;
        }
    }

    public class CoApplicantDetail {
        public String coApplicantName;        // Co-applicant name
        public String coApplicantCareOf;      // Care of information
        public String coApplicantAadharNumber; // Aadhaar number (masked)
        public String coApplicantPANNumber;   // PAN number
    }

    public class MilestoneDetail {
        public String milestoneName;              // Milestone name
        public String milestoneDate;              // Milestone date
        public Integer milestonePaymentPercentage; // Payment percentage
        public String milestoneAmount;            // Total milestone amount
        public String milestonePaidAmount;        // Amount paid
        public String milestonePendingAmount;     // Pending amount
        public String milestoneStatus;            // Milestone status
    }

    public class HomeScreenData {
        public Decimal percentagePaymentDone;        // Payment percentage
        public String paidAmount;                    // Total paid amount
        public String balanceAmount;                 // Balance amount
        public PropertyDetail propertyDetail;        // Property information
        public List<NewLaunch> newLaunch;            // New launches
        public Integer demandCount;
        public Integer propertyCount;                  // Total demands
        public Integer payments;                     // Total payments
        public Integer documents;                    // Total documents
        public Integer raiseQuery;                   // Total queries/issues
        public Integer referrals;                    // Total referrals        
        public Boolean unReadNotification;
        public List<CoApplicantDetail> coApplicantsDetails; // Co-applicants
        public List<MilestoneDetail> projectMilestones;     // Project milestones
    }

    public class HomeScreenResponse {
        public Boolean status;           // Response status
        public String message;           // Response message
        public HomeScreenData data;      // Response data
    }

    private static String formatAmountInLakhs(Decimal amount) {
        Decimal safeAmount = amount != null ? amount : 0;
        Decimal amountInLakhs = safeAmount / 100000;
        return String.valueOf(amountInLakhs.setScale(2)) + 'L';
    }

    private static String formatDateAsIsoUtc(Date inputDate) {
        if (inputDate == null) {
            return '';
        }
        Datetime dateTimeValue = Datetime.newInstanceGMT(inputDate.year(), inputDate.month(), inputDate.day(), 12, 34, 56);
        return dateTimeValue.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
    }

}