force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Quote__r.GRAND_TOTAL__c /*Total_Cost_of_the_Flat__c + GST_5__c*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/Demand_Raised__c.object-meta.xml
<CustomObject>
    <label>Demand Raised</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>Demand Raised Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Raised</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand_Raised__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Demand_Status__c.field-meta.xml
<CustomField>
    <fullName>Demand_Status__c</fullName>
    <label>Demand Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demand Raised</fullName>
                <default>true</default>
                <label>Demand Raised</label>
            </value>
            <value>
                <fullName>Demand Cancelled</fullName>
            </value>
            <value>
                <fullName>Demand Reversed</fullName>
            </value>
            <value>
                <fullName>Credit Note Issued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Refund__c/Refund__c.object-meta.xml
<CustomObject>
    <label>Refund</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Refund__c/fields/Refund_Type__c.field-meta.xml
<CustomField>
    <fullName>Refund_Type__c</fullName>
    <label>Refund Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>Refund Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Refund__c/fields/Reversed_Demand__c.field-meta.xml
<CustomField>
    <fullName>Reversed_Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reversed Demand</label>
    <referenceTo>Demand_Raised__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RefundController.cls
public class RefundController {
    @AuraEnabled(cacheable=true)
    public static Demand_Raised__c getDemandDetails(Id demandId) {
        return [
            SELECT Id, Name, Grand_Total__c, Demand_Status__c, Booking__r.Name, 
            CreatedDate
            FROM Demand_Raised__c 
            WHERE Id = :demandId
            LIMIT 1
        ];
    }
    
    @AuraEnabled
    public static Id cancelDemandAndCreateRefund(Id demandId) {
        Demand_Raised__c demand = [
            SELECT Id, Grand_Total__c
            FROM Demand_Raised__c
            WHERE Id = :demandId
            LIMIT 1
        ];
        
        if (demand == null) {
            throw new AuraHandledException('Demand not found.');
        }
        
        // Create Refund
        Refund__c refund = new Refund__c();
        refund.Refund_Amount__c = demand.Grand_Total__c;
        refund.Reversed_Demand__c = demand.Id;
        refund.Refund_Type__c = 'Credit Note';
        insert refund;
        
        // Update Demand
        demand.Demand_Status__c = 'Demand Cancelled';
        update demand;
        
        // Return newly created refund record Id
        return refund.Id;
    }
}