force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>GRAND_TOTAL__c+ Total_Interest__c - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending_Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Completed_Date_New__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date_New__c</fullName>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Payable_Amount__c   - Received_Amount1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Received_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount1__c</fullName>
    <label>Received_Amount</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status_Picklist__c</field>
        <operation>notEqual</operation>
        <value>Rejected</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/PaymentScheduleReminderBatch.cls
global class PaymentScheduleReminderBatch implements Database.Batchable<SObject>, Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Name, Completed_Date_New__c,Pending_Amount__c, S_No__c, Booking__c, Received_Amount1__c, Demanded_Date__c
            FROM Payment_schedule__c
            WHERE Completed_Date_New__c = :System.today() ]);
    }
    
    global void execute(Database.BatchableContext bc, List<Payment_schedule__c> scope) {
        Map<String, Decimal> bookingsWithPSNO = new Map<String, Decimal>();
        for (Payment_schedule__c ps : scope) {
            if (ps.Booking__c != null && ps.S_No__c != null) {
                bookingsWithPSNO.put(ps.Booking__c, ps.S_No__c);
            }
        }
        // Call your method only if map has data
        if (!bookingsWithPSNO.isEmpty()) {
            DemandRaisedSave.bulkAutoDemands(bookingsWithPSNO);
        }
        
    }
    
    global void finish(Database.BatchableContext bc) {
        // Optional: send summary email or log
    }
}