force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Aadhar_No__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_No__c</fullName>
    <label>Aadhaar No.</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Application_Amount__c.field-meta.xml
<CustomField>
    <fullName>Application_Amount__c</fullName>
    <label>Application Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Flat_no__c.field-meta.xml
<CustomField>
    <fullName>Flat_no__c</fullName>
    <label>Flat no</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Quote__r.GRAND_TOTAL__c /*Total_Cost_of_the_Flat__c + GST_5__c*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>GRAND_TOTAL__c+ Total_Interest__c - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending_Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Quote__r.Agreement_Value_after_GST__c</formula>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_received_Amount__c</fullName>
    <label>Total_received_Amount</label>
    <summarizedField>Receipt__c.Total_Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Approval_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Payment_Type__c</field>
        <operation>notEqual</operation>
        <value>Additional Charges</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit_No__c.field-meta.xml
<CustomField>
    <fullName>Unit_No__c</fullName>
    <formula>Plot__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co Applicant</label>
    <nameField>
        <label>Co Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Co Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Applicant__c/fields/Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address__c</fullName>
    <label>Permanent Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/Demand_Raised__c.object-meta.xml
<CustomObject>
    <label>Demand Raised</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>Demand Raised Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Raised</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand_Raised__c/fields/Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Amount_Demanded__c</fullName>
    <label>Amount_Demanded</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Booking__r.Project1__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BookingDemandInvoice.cls
public with sharing class BookingDemandInvoice {
    public Booking__c booking { get; set; }
    public List<Co_Applicant__c> coApplicants { get; set; }
    public String demandName{ get; set; }
    public decimal taxableValue{ get; set; }
    public decimal totalvalue{ get; set; }
    public decimal cgstvalue{ get; set; }
    
    public decimal sgstvalue{ get; set; }
    public decimal cgst{get;set;}
    public decimal sgst{get;set;}

    public BookingDemandInvoice(ApexPages.StandardController stdCtrl) {
        booking = (Booking__c) stdCtrl.getRecord();
        System.debug(booking);
        coApplicants = new List<Co_Applicant__c>();
      
        
        List<Booking__c> bookingList = [ SELECT Id,Project1__c,Project1__r.GST_on_Aggrement__c, Name, Applicant_Name__c, First_Applicant_Name__c, Mobile__c, Email__c, Address__c, Permanent_Address__c, Project__c, Project1__r.Name, Flat_no__c, Unit_No__c, GRAND_TOTAL__c, Booking_Date__c, Application_Amount__c, Booking_Amount__c, Total__c, Total_received_Amount__c, Pending_Amount__c, PAN_Number__c, Aadhar_No__c FROM Booking__c WHERE Id = :booking.Id LIMIT 1 ];


        if (!bookingList.isEmpty()) {
            booking = bookingList[0];
        }
        System.debug(bookingList);
        coApplicants = [ SELECT Id, Name, PAN_Number__c FROM Co_Applicant__c WHERE Booking__c = :booking.Id ];
        Demand_Raised__c dr = [select id,Name,Amount_Demanded__c from Demand_Raised__c where Booking__c =: booking.Id];
        system.debug(dr);
        demandName = dr.Name;
        taxableValue = dr.Amount_Demanded__c;
        cgstvalue=dr.Amount_Demanded__c *bookingList[0].Project1__r.GST_on_Aggrement__c;
        sgstvalue=dr.Amount_Demanded__c *bookingList[0].Project1__r.GST_on_Aggrement__c;
        cgst=bookingList[0].Project1__r.GST_on_Aggrement__c/2;
         sgst=bookingList[0].Project1__r.GST_on_Aggrement__c/2;              
    }
    
}