force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Demands &amp; Collections</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Hand Over</fullName>
            </value>
            <value>
                <fullName>Swapping</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Payment_percent__c.field-meta.xml
<CustomField>
    <fullName>Payment_percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment percent</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Demanded</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rc-{0000}</displayFormat>
        <label>Receipt No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Receipt Line Item</label>
    <nameField>
        <label>Receipt Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>TEXT(Receipt__r.Approval_status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Cheque_no_Transaction_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_no_Transaction_Number__c</fullName>
    <label>Cheque no / Transaction Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <label>Payment schedule</label>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RecreatingPaymentSchedulesTest.cls
@isTest
public class RecreatingPaymentSchedulesTest {

@isTest
    static void tstingsetup() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User user1 = new User(
            Alias = 'Fin',
            Email = 'FinanceUser@example.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/New_York',
            UserName = 'FinanceUser664323@example.com',
            ContactId = null,
            FirstName = 'User',
            LastName = 'One'
        );
        insert user1;
        
        User user2 = new User(
            Alias = 'Leg',
            Email = 'LegalUser@example.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/New_York',
            UserName = 'LegalUser00965@example.com',
            ContactId = null,
            FirstName = 'Legal',
            LastName = 'User'
        );
        insert user2;
        
        User user3 = new User(
            Alias = 'Res',
            Email = 'ReservationUser@example.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/New_York',
            UserName = 'ReservationUser22123@example.com',
            ContactId = null,
            FirstName = 'Reservation',
            LastName = 'User'
        );
        insert user3;
        User user4 = new User(
            Alias = 'CRM',
            Email = 'CRMManager@example.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/New_York',
            UserName = 'CRMManager665434@example.com',
            ContactId = null,
            FirstName = 'CRM',
            LastName = 'Manager'
        );
        insert user4;
        // Create Projects
        
     

            
            
            
            // Create Booking
            Booking__c booking = new Booking__c(
                Stage__c = 'New'
            );
        insert booking;
        
      
        
        // Create Receipt
        Receipt__c receipt = new Receipt__c(Booking__c = booking.Id,Finance_User__c= user1.Id, Approval_status__c = 'Approved',Receipt_date__c = system.today(),Amount_received__c = 1000);
        insert receipt;
        
        Master_payment_schedule__c mpy = new Master_payment_schedule__c ();
        mpy.Status__c = 'Completed';
        
        Master_payment_schedule__c mpy1 = new Master_payment_schedule__c ();
        mpy1.Status__c = 'Progress';
        
        Payment_schedule__c pys = new Payment_schedule__c();
        pys.Payment_Percent__c=100;
        pys.Payment_Due_Date__c = system.today()-10;
        pys.Booking__c = booking.id;
        pys.Master_Payment_Schedule__c = mpy .Id;
        pys.name ='on booking';
        pys.Interest_Percent__c=20;
        insert pys;
      
        
        // Create Receipt Line Item
        Receipt_Line_Item__c receiptLineItem = new Receipt_Line_Item__c(
            Name = 'Receipt Line Item 1',
            Receipt__c = receipt.Id,
            Booking__c = booking.Id,
            Amount__c = 1000,
            Payment_schedule__c = pys.Id,
            Cheque_no_Transaction_Number__c = '11223555555'
        );
        
        insert receiptLineItem;
        
        
        RecreatingPaymentSchedules.recreateReceipts(booking.Id);
        RecreatingPaymentSchedules.testCoverage();
    }
    
}