force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Quote__r.GRAND_TOTAL__c /*Total_Cost_of_the_Flat__c + GST_5__c*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <formula>Project1__r.GST_on_Aggrement__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Apartments.recordType-meta.xml
<RecordType>
    <fullName>Apartments</fullName>
    <active>true</active>
    <label>Apartments</label>
</RecordType>

force-app/main/default/objects/Booking__c/recordTypes/Plots.recordType-meta.xml
<RecordType>
    <fullName>Plots</fullName>
    <active>true</active>
    <label>Plots</label>
</RecordType>

force-app/main/default/objects/Demand_Raised__c/Demand_Raised__c.object-meta.xml
<CustomObject>
    <label>Demand Raised</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>Demand Raised Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Raised</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand_Raised__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Current_Demand_amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Demand_amount__c</fullName>
    <label>Current Demand amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Demand_Name__c.field-meta.xml
<CustomField>
    <fullName>Demand_Name__c</fullName>
    <label>Demand Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <formula>Booking__r.GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment schedule</label>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Last_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Last Payment Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Agreement_Value_Before_GST__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Before_GST__c</fullName>
    <formula>IF(
   RecordType.Name = &apos;Apartments&apos;,

    /* APARTMENT - Full Calculation */
(Rate_per_sqft__c * Super_Built_UpArea__c )+
(Unit__r.Floor_Rise_Charge__c * Super_Built_UpArea__c) +
(Unit__r.East_Facing_Charges__c * Super_Built_UpArea__c) +
(Unit__r.Corner_Charges__c * Super_Built_UpArea__c) +
(Unit__r.Road_View_Charges__c * Super_Built_UpArea__c )+
(Unit__r.ORR_View_Charges__c * Super_Built_UpArea__c) +
(Unit__r.Garden_View_Charges__c * Super_Built_UpArea__c) +
(Unit__r.Clubhouse_Charges__c) +
(Unit__r.Water_Electricity_Charges__c) +
(Unit__r.Car_Parking__c),

    /* PLOT - Simple Calculation */
    Base_Value__c + Total_Infrastructure_Charges__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Value Before GST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>if( RecordType.Name ==&apos;Apartments&apos;,Other_Charges_after_GST__c+Agreement_Value_after_GST__c, (Total_Sales_Consideration__c+GST_On_Other_Charges_Actual__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/Apartments.recordType-meta.xml
<RecordType>
    <fullName>Apartments</fullName>
    <active>true</active>
    <label>Apartments</label>
</RecordType>

force-app/main/default/objects/Quote__c/recordTypes/Plots.recordType-meta.xml
<RecordType>
    <fullName>Plots</fullName>
    <active>true</active>
    <label>Plots</label>
</RecordType>

force-app/main/default/classes/Demand_Note_send_Controller_Test.cls
@isTest
public class Demand_Note_send_Controller_Test {
    
    @isTest
    static void testControllerWithGST() {
        // Create Account
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        // Create RecordType for Apartments
        RecordType apartmentRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Booking__c' AND DeveloperName = 'Apartments' LIMIT 1];
        
        // Create Quote__c with GST
        Quote__c quote = new Quote__c(
            Quote_date__c = System.today(),
            With_GST__c = true
           // Agreement_Value_Before_GST__c = 6000000 // > 50 lakhs for TDS
        );
        insert quote;
        
        // Create Booking__c with GST
        Booking__c booking = new Booking__c(
            Bank_Name__c = 'Test Booking',
            Quote__c = quote.Id,
            //GST__c = 18,
            RecordTypeId = apartmentRT.Id
        );
        insert booking;
        
        // Create Payment_schedule__c
        Payment_schedule__c ps = new Payment_schedule__c(
            Name = 'Test Payment Schedule',
            Booking__c = booking.Id,
           Last_Payment_Schedule__c = true
        );
        insert ps;
        
        // Create Demand_Raised__c
        Demand_Raised__c demand = new Demand_Raised__c(
            Demand_Name__c = 'Test Demand',
            Booking__c = booking.Id,
            Payment_schedule__c = ps.Id,
            Current_Demand_amount__c = 118000,
            Grand_Total__c = 118000
          // GST__c = 18
        );
        insert demand;
        
        Test.startTest();
        PageReference pageRef = new PageReference('/apex/Demand_Note_send?Id=' + demand.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(demand);
        Demand_Note_send_Controller controller = new Demand_Note_send_Controller(sc);
        Test.stopTest();
        
    
    }
    
    @isTest
    static void testControllerPlotsLastPayment() {
        // Create RecordType for Plots
        RecordType plotRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Booking__c' AND DeveloperName = 'Plots' LIMIT 1];
        
        // Create Quote__c with GST
        Quote__c quote = new Quote__c(
            Quote_date__c = System.today(),
            With_GST__c = true
            //Agreement_Value_Before_GST__c = 4000000 // < 50 lakhs for TDS test
        );
        insert quote;
        
        // Create Booking__c for Plots
        Booking__c booking = new Booking__c(
            Bank_Name__c = 'Test Booking Plot',
            Quote__c = quote.Id,
          //  GST__c = 18,
            RecordTypeId = plotRT.Id
        );
        insert booking;
        
        // Create Payment_schedule__c - Last Payment
        Payment_schedule__c ps = new Payment_schedule__c(
            Name = 'Test Payment Schedule Last',
            Booking__c = booking.Id
           // Last_Payment_Schedule__c = true
        );
        insert ps;
        
        // Create Demand_Raised__c
        Demand_Raised__c demand = new Demand_Raised__c(
            Demand_Name__c = 'Test Demand Plot',
            Booking__c = booking.Id,
            Payment_schedule__c = ps.Id,
            Current_Demand_amount__c = 50000
        );
        insert demand;
        
        Test.startTest();
        PageReference pageRef = new PageReference('/apex/Demand_Note_send?Id=' + demand.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(demand);
        Demand_Note_send_Controller controller = new Demand_Note_send_Controller(sc);
        Test.stopTest();
        

    }
    
    @isTest
    static void testControllerPlotsNonLastPayment() {
        // Create RecordType for Plots
        RecordType plotRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Booking__c' AND DeveloperName = 'Plots' LIMIT 1];
        
        // Create Quote__c with GST
        Quote__c quote = new Quote__c(
            Quote_date__c = System.today(),
            With_GST__c = true
          //  Agreement_Value_Before_GST__c = 3000000
        );
        insert quote;
        
        // Create Booking__c for Plots
        Booking__c booking = new Booking__c(
            Bank_Name__c = 'Test Booking Plot Regular',
            Quote__c = quote.Id,
           // GST__c = 12,
            RecordTypeId = plotRT.Id
        );
        insert booking;
        
        // Create Payment_schedule__c - NOT Last Payment
        Payment_schedule__c ps = new Payment_schedule__c(
            Name = 'Test Payment Schedule Regular',
            Booking__c = booking.Id
          //  Last_Payment_Schedule__c = false
        );
        insert ps;
        
        // Create Demand_Raised__c
        Demand_Raised__c demand = new Demand_Raised__c(
            Demand_Name__c = 'Test Demand Plot Regular',
            Booking__c = booking.Id,
            Payment_schedule__c = ps.Id,
            Current_Demand_amount__c = 30000
        );
        insert demand;
        
        Test.startTest();
        PageReference pageRef = new PageReference('/apex/Demand_Note_send?Id=' + demand.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(demand);
        Demand_Note_send_Controller controller = new Demand_Note_send_Controller(sc);
        Test.stopTest();
        
      
    }
    
    @isTest
    static void testControllerWithoutGST() {
        // Create Quote__c WITHOUT GST
        Quote__c quote = new Quote__c(
            Quote_date__c = System.today(),
            With_GST__c = false
            //Agreement_Value_Before_GST__c = 2000000
        );
        insert quote;
        
        // Create Booking__c
        Booking__c booking = new Booking__c(
            Bank_Name__c = 'Test Booking No GST',
            Quote__c = quote.Id
        );
        insert booking;
        
        // Create Payment_schedule__c
        Payment_schedule__c ps = new Payment_schedule__c(
            Name = 'Test Payment Schedule',
            Booking__c = booking.Id
        );
        insert ps;
        
        // Create Demand_Raised__c
        Demand_Raised__c demand = new Demand_Raised__c(
            Demand_Name__c = 'Test Demand No GST',
            Booking__c = booking.Id,
            Payment_schedule__c = ps.Id,
            Current_Demand_amount__c = 100000
        );
        insert demand;
        
        Test.startTest();
        PageReference pageRef = new PageReference('/apex/Demand_Note_send?Id=' + demand.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(demand);
        Demand_Note_send_Controller controller = new Demand_Note_send_Controller(sc);
        Test.stopTest();
       
    }
}