force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Aadhar_No__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_No__c</fullName>
    <label>Aadhaar No.</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Agreement_Execution_Date__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Execution_Date__c</fullName>
    <formula>DATEVALUE(Booking_Approval_Time__c) + (30 + Extension_Days__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Execution Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Communication_Address__c.field-meta.xml
<CustomField>
    <fullName>Communication_Address__c</fullName>
    <label>Communication Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Employeed_at__c.field-meta.xml
<CustomField>
    <fullName>Employeed_at__c</fullName>
    <label>Employeed at</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Quote__r.GRAND_TOTAL__c /*Total_Cost_of_the_Flat__c + GST_5__c*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Office_Address1__c.field-meta.xml
<CustomField>
    <fullName>Office_Address1__c</fullName>
    <label>Office Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Other_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Other_Qualification__c</fullName>
    <label>Other Qualification</label>
    <length>132</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Permanent_Address2__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address2__c</fullName>
    <label>Permanent Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pincode_office__c.field-meta.xml
<CustomField>
    <fullName>Pincode_office__c</fullName>
    <label>Office Pincode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/S__c.field-meta.xml
<CustomField>
    <fullName>S__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>M/s.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Son_Daughter_Wife_of__c.field-meta.xml
<CustomField>
    <fullName>Son_Daughter_Wife_of__c</fullName>
    <label>S/o,D/o,W/o</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S/o</fullName>
            </value>
            <value>
                <fullName>D/o</fullName>
            </value>
            <value>
                <fullName>W/o</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Spouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Spouse_Name__c</fullName>
    <label>Spouse Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Plots.recordType-meta.xml
<RecordType>
    <fullName>Plots</fullName>
    <active>true</active>
    <label>Plots</label>
</RecordType>

force-app/main/default/objects/Booking__c/recordTypes/Villas.recordType-meta.xml
<RecordType>
    <fullName>Villas</fullName>
    <active>true</active>
    <label>Villas</label>
</RecordType>

force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co Applicant</label>
    <nameField>
        <label>Co Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Co Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Applicant__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhaar Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Alternate_Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Contact_No__c</fullName>
    <label>Alternate Contact No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Communication_Address__c.field-meta.xml
<CustomField>
    <fullName>Communication_Address__c</fullName>
    <label>Communication Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <label>Country of Residence</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Employeed_at__c.field-meta.xml
<CustomField>
    <fullName>Employeed_at__c</fullName>
    <label>Company/firm Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Ancillary</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>FMCG</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>Consumer Durables</fullName>
            </value>
            <value>
                <fullName>Defense Service</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Metal and Mining</fullName>
            </value>
            <value>
                <fullName>Oil, Gas and Power</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Textiles</fullName>
            </value>
            <value>
                <fullName>Service Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Office_Address1__c.field-meta.xml
<CustomField>
    <fullName>Office_Address1__c</fullName>
    <label>Office Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Office_Address__c.field-meta.xml
<CustomField>
    <fullName>Office_Address__c</fullName>
    <label>Office Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Office_Pincode__c.field-meta.xml
<CustomField>
    <fullName>Office_Pincode__c</fullName>
    <label>Office Pincode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Other_Industry__c.field-meta.xml
<CustomField>
    <fullName>Other_Industry__c</fullName>
    <label>Other Industry</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Other_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Other_Qualification__c</fullName>
    <label>Other Qualification</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Permanent_Address1__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address1__c</fullName>
    <label>Permanent Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address__c</fullName>
    <label>Permanent Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Pincode_commmunication__c.field-meta.xml
<CustomField>
    <fullName>Pincode_commmunication__c</fullName>
    <label>Communication PinCode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Pincode_office__c.field-meta.xml
<CustomField>
    <fullName>Pincode_office__c</fullName>
    <label>Office Pincode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Pincode_permanent__c.field-meta.xml
<CustomField>
    <fullName>Pincode_permanent__c</fullName>
    <label>Permanent Pincode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Post Graduate</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>M/s.</fullName>
            </value>
            <value>
                <fullName>Shri</fullName>
                <isActive>false</isActive>
                <label>Shri</label>
            </value>
            <value>
                <fullName>Smt</fullName>
                <isActive>false</isActive>
                <label>Smt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Son2_Daughter_Wife_of__c.field-meta.xml
<CustomField>
    <fullName>Son2_Daughter_Wife_of__c</fullName>
    <label>S/o,D/o,W/o</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S/o</fullName>
            </value>
            <value>
                <fullName>D/o</fullName>
            </value>
            <value>
                <fullName>W/o</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Spouse_Date_Of_Birth_coapp__c.field-meta.xml
<CustomField>
    <fullName>Spouse_Date_Of_Birth_coapp__c</fullName>
    <label>Spouse Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Co_Applicant__c/fields/Spouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Spouse_Name__c</fullName>
    <label>Spouse Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plot__c/recordTypes/Plot.recordType-meta.xml
<RecordType>
    <fullName>Plot</fullName>
    <active>true</active>
    <label>Plot</label>
</RecordType>

force-app/main/default/objects/Plot__c/recordTypes/Villa.recordType-meta.xml
<RecordType>
    <fullName>Villa</fullName>
    <active>true</active>
    <label>Villa</label>
</RecordType>

force-app/main/default/classes/CancellationLetterVFPController.cls
public class CancellationLetterVFPController {
    public Id bookingId { get; set; }
    public List<Co_Applicant__c> coApplicants { get; set; }
     public Co_Applicant__c firstCoApplicant { get; set; }
        public Booking__c booking { get; set; }
    public String projectLogoUrl { get; set; }
    public String unitLabel { get; set; }
    public String projectName { get; set; }
    
    
    private Boolean bookingAddressesLoaded = false;
    private Address permanentAddress;
    
    public CancellationLetterVFPController(ApexPages.StandardController stdController) {
        bookingId = stdController.getId();
         fetchBookingDetails();
        coapplicants=[
            SELECT Name, Salutation__c, Date_of_Birth__c, Spouse_Date_Of_Birth_coapp__c,Spouse_Name__c,
                   Permanent_Address__c, Communication_Address__c, Pincode_office__c,Other_Qualification__c,
                   Qualification__c, Pincode_commmunication__c, Pincode_permanent__c,Other_Industry__c,
                   Office_Address__c, Anniverssary_Date__c, Son_Daughter_Wife_of__c,Son2_Daughter_Wife_of__c,
                   Nationality__c, Co_Applicant__c.Aadhar_Number__c, Alternate_Contact_No__c,Country_of_Residence__c,
                   Passport_Number__c, PAN_Number__c, Email__c, Primary_Phone__c,Office_Pincode__c,
                   Residential_Status__c, Profession__c, Industry__c, Employeed_at__c, Designation__c,Communication_Address1__Street__s,
            Communication_Address1__City__s,Communication_Address1__CountryCode__s,Communication_Address1__PostalCode__s,Communication_Address1__StateCode__s,
            Permanent_Address1__Street__s,Permanent_Address1__City__s,Permanent_Address1__CountryCode__s,Permanent_Address1__PostalCode__s,Permanent_Address1__StateCode__s,
            Office_Address1__Street__s,Office_Address1__City__s,Office_Address1__CountryCode__s,Office_Address1__PostalCode__s,Office_Address1__StateCode__s
            FROM Co_Applicant__c WHERE Booking__c = :bookingId  ];
      
        if (!coApplicants.isEmpty()) {
            firstCoApplicant = coApplicants[0];
        }
       
    }
     public void  fetchBookingDetails(){
         booking = [Select Id,
                   First_Applicant_Name__c,
                   Agreement_Execution_Date__c,
                   S__c,
                   Son_Daughter_Wife_of1__c,
                   PAN_Number__c,
                   Agreement_Executed_Date__c,
                   Aadhar_No__c,
                   Address__c,
                   Date_of_Birth1__c,
                   Son_Daughter_Wife_of__c,
                   Booking_Amount__c,
                   GRAND_TOTAL__c,
                   Permanent_Address1__c,
                   Correspondence_Address__Street__s,
                   Correspondence_Address__City__s,
                   Correspondence_Address__PostalCode__s,
                   Correspondence_Address__StateCode__s,
                   Pincode1__c,
                   Permanent_Address2__c,
                   Plot__c,
                   Project1__r.Name,
                   Project1__r.Project_Logo_Url__c,
                   Project1__r.Project_Type__c


                   From Booking__c Where Id=:bookingId];
        projectName = booking.Project1__r.Name;
        projectLogoUrl = booking.Project1__r.Project_Logo_Url__c;
        unitLabel = getUnitLabelFromType(booking.Project1__r.Project_Type__c);
    }

    public static String getUnitLabelFromType(String projectType) {
        if (projectType == 'Plots') return 'Plot';
        if (projectType == 'Villas') return 'Villa';
        return 'Unit';
    }
   
    private void loadBookingAddresses() {
        if (bookingAddressesLoaded) return;
        
        Booking__c b = [
            SELECT Permanent_Address2__c,
            Correspondence_Address__c,
            Office_Address1__c
            FROM Booking__c
            WHERE Id = :booking.Id
            LIMIT 1
        ];
        
        permanentAddress      = b.Permanent_Address2__c;
        
        bookingAddressesLoaded = true;
    }
    public String getPermanentFullAddress() {
        loadBookingAddresses();            // you already have this
        return formatAddress(permanentAddress);
    }
    private String formatAddress(Address addr) {
        if (addr == null) return '';
        
        List<String> parts = new List<String>();
        
        if (!String.isBlank(addr.street))  parts.add(addr.street);
        if (!String.isBlank(addr.city))    parts.add(addr.city);
        if (!String.isBlank(addr.state))   parts.add(addr.state);
        if (!String.isBlank(addr.postalcode))   parts.add(addr.postalcode);
        if (!String.isBlank(addr.country)) parts.add(addr.country);
        
        return String.join(parts, ', ');
    }
    
    
}