force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/GRAND_TOTAL__c.field-meta.xml
<CustomField>
    <fullName>GRAND_TOTAL__c</fullName>
    <formula>Quote__r.GRAND_TOTAL__c /*Total_Cost_of_the_Flat__c + GST_5__c*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRAND TOTAL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <formula>Project1__r.GST_on_Aggrement__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SAC_HSN_Code__c.field-meta.xml
<CustomField>
    <fullName>SAC_HSN_Code__c</fullName>
    <formula>&apos;gg&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAC/HSN Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Apartments.recordType-meta.xml
<RecordType>
    <fullName>Apartments</fullName>
    <active>true</active>
    <label>Apartments</label>
</RecordType>

force-app/main/default/objects/Booking__c/recordTypes/Plots.recordType-meta.xml
<RecordType>
    <fullName>Plots</fullName>
    <active>true</active>
    <label>Plots</label>
</RecordType>

force-app/main/default/objects/Demand_Raised__c/Demand_Raised__c.object-meta.xml
<CustomObject>
    <label>Demand Raised</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>Demand Raised Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Raised</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand_Raised__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Current_Demand_amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Demand_amount__c</fullName>
    <label>Current Demand amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <formula>Booking__r.GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Milestone_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Percentage__c</fullName>
    <label>Milestone Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment schedule</label>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <formula>IF(
  Is_Clubhouse_Charges__c, Booking__r.Clubhouse_Charges__c,
  IF(Is_Infrastructure_Charges__c, Booking__r.Total_Infrastructure_Charges__c,
    IF(Is_Maintenance_Charges__c, Booking__r.Total_Maintenance_Amount__c,
      IF(
        Booking__r.RecordType.DeveloperName &lt;&gt; &apos;Plots&apos;,
        Payment_percent__c * Quote__r.GRAND_TOTAL__c,
										(Booking__r.Agreement_Value__c - Booking__r.Total_Infrastructure_Charges__c) * Payment_percent__c)))
     
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AmountB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Last_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Last Payment Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Milestone_Amount_Without_GST__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Amount_Without_GST__c</fullName>
    <formula>Booking__r.Agreement_Value__c * Payment_percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone Amount Without GST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Demand_Note_send_Controller.cls
public class Demand_Note_send_Controller {
    public Decimal cgst { get; set; }
    public Decimal sgst { get; set; }
    public Decimal taxableValue { get; set; }
    public String demandId { get; set; }
    public Demand_Raised__c demand { get; set; }
    public Decimal TDSonePercentage { get; set; }
    public Boolean showGSTBreakdown { get; set; }
    
    public String SANHSNCode { get; set; }
    
    public Demand_Note_send_Controller(ApexPages.StandardController controller) {
        TDSonePercentage = 0;
        taxableValue = 0;
        cgst = 0;
        sgst = 0;
        showGSTBreakdown = false;
        
        demandId = ApexPages.currentPage().getParameters().get('Id');
        
        List<Demand_Raised__c> dmList = [
            SELECT Id, Grand_Total__c, GST__c, Current_Demand_amount__c, Milestone_Percentage__c,
            Booking__r.Quote__r.With_GST__c, Booking__r.Quote__r.Agreement_Value_Before_GST__c, 
            Booking__r.GST__c, Booking__r.RecordType.DeveloperName,
            Payment_schedule__r.Last_Payment_Schedule__c,
            Payment_schedule__r.AmountB__c,
            Payment_schedule__r.Milestone_Amount_Without_GST__c,Payment_schedule__r.SAC_HSN_Code__c
            FROM Demand_Raised__c 
            WHERE Id = :demandId 
            LIMIT 1
        ];
        
        System.debug('dmList: ' + dmList);
        
        if (!dmList.isEmpty()) {
            demand = dmList[0];
            SANHSNCode = demand.Payment_schedule__r.SAC_HSN_Code__c;
            // FIXED: Get both amounts
            Decimal presentDue = demand.Current_Demand_amount__c != null ? demand.Current_Demand_amount__c : 0;
            Decimal milestoneAmountWithoutGST = demand.Payment_schedule__r.Milestone_Amount_Without_GST__c != null ? 
                                               demand.Payment_schedule__r.Milestone_Amount_Without_GST__c : 0;
            
            Decimal gstPercentage = (demand.Booking__r.GST__c != null) ? demand.Booking__r.GST__c / 100 : 0;
            Decimal currentMilestonePaymentPercent = demand.Milestone_Percentage__c != null ? demand.Milestone_Percentage__c : 0;
            
            Boolean isPlot = (demand.Booking__r.RecordType.DeveloperName == 'Plots');
            Boolean isLastPayment = (demand.Payment_schedule__r.Last_Payment_Schedule__c == true);
            Boolean hasGST = (demand.Booking__r.Quote__r.With_GST__c == true);
            
            // FIXED: Match DemandInvoiceController logic
            // Calculate taxable value and GST for CURRENT MILESTONE only
            // GST breakdown should ONLY show on LAST PAYMENT for both Plots and Apartments
            if (presentDue != null && presentDue > 0) {
                if (isLastPayment ) {
                    // Only process GST breakdown on last payment with GST
                    showGSTBreakdown = false;
                    
                    if (isPlot) {
                        // For Plots: Show GST breakdown on last payment
                        showGSTBreakdown = true;
                    } else {
                        // For Apartments: Show GST breakdown on last payment
                        showGSTBreakdown = true;
                    }
                    
                    if (showGSTBreakdown) {
                        // Calculate GST breakdown
                        // presentDue (AmountB__c) includes GST on last payment
                        // Reverse calculate to get base amount
                        taxableValue = demand.Payment_schedule__r.Milestone_Amount_Without_GST__c;
                        cgst = ((demand.Payment_schedule__r.AmountB__c - demand.Payment_schedule__r.Milestone_Amount_Without_GST__c) / 2).setScale(2);
                        sgst = ((demand.Payment_schedule__r.AmountB__c - demand.Payment_schedule__r.Milestone_Amount_Without_GST__c) / 2).setScale(2);
                        
                        // Validation: taxableValue should match milestoneAmountWithoutGST
                        System.debug('Calculated taxableValue: ' + taxableValue);
                        System.debug('Milestone_Amount_Without_GST__c: ' + milestoneAmountWithoutGST);
                    } else {
                        // No GST breakdown
                        taxableValue = milestoneAmountWithoutGST;
                        cgst = 0;
                        sgst = 0;
                    }
                } else {
                    // Not last payment OR no GST - no GST breakdown
                    // AmountB__c = Milestone_Amount_Without_GST__c in this case
                    taxableValue = milestoneAmountWithoutGST;
                    cgst = 0;
                    sgst = 0;
                }
            } else {
                // No present due amount
                taxableValue = 0;
                cgst = 0;
                sgst = 0;
            }
            
            // TDS Calculation - 1% of current milestone payment percent of Agreement Value Before GST if > 50 lakhs
            Decimal totalSalesConsideration = demand.Booking__r.Quote__r.Agreement_Value_Before_GST__c != null ? 
                                             demand.Booking__r.Quote__r.Agreement_Value_Before_GST__c : 0;
            TDSonePercentage = totalSalesConsideration > 5000000 ? 
                (totalSalesConsideration * (currentMilestonePaymentPercent / 100) * 0.01).setScale(0) : 0;
            
            System.debug('isPlot: ' + isPlot);
            System.debug('isLastPayment: ' + isLastPayment);
            System.debug('hasGST: ' + hasGST);
            System.debug('showGSTBreakdown: ' + showGSTBreakdown);
            System.debug('presentDue (AmountB__c): ' + presentDue);
            System.debug('milestoneAmountWithoutGST: ' + milestoneAmountWithoutGST);
            System.debug('taxableValue: ' + taxableValue);
            System.debug('cgst: ' + cgst);
            System.debug('sgst: ' + sgst);
            System.debug('currentMilestonePaymentPercent: ' + currentMilestonePaymentPercent);
            System.debug('TDSonePercentage: ' + TDSonePercentage);
            System.debug('totalSalesConsideration: ' + totalSalesConsideration);
        }
    }
}