force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rc-{0000}</displayFormat>
        <label>Receipt No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Check_Transaction_Nmber__c.field-meta.xml
<CustomField>
    <fullName>Check_Transaction_Nmber__c</fullName>
    <label>Cheque no / Transaction Number</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Mode_Of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Payment__c</fullName>
    <label>Mode Of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>NetBanking</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
            <value>
                <fullName>Net Banking</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReceiptLineItemBatchTest.cls
@isTest
private class ReceiptLineItemBatchTest {

    @isTest
    static void testBatchExecutes() {

        Booking__c booking = new Booking__c();
        insert booking;

        Payment_Schedule__c ps = new Payment_Schedule__c();
        ps.Booking__c          = booking.Id;
        ps.S_No__c             = 1;
        insert ps;

        Receipt__c rc             = new Receipt__c();
        rc.Booking__c             = booking.Id;
        rc.Manual_Upload__c       = true;
        rc.Receipt_Date__c        = Date.newInstance(2024, 1, 1);
        rc.Amount_Received__c     = 50000;
        rc.Mode_Of_Payment__c     = 'NEFT';
        rc.Check_Transaction_Nmber__c = 'TXN001';
        insert rc;

        Test.startTest();
        Database.executeBatch(new ReceiptLineItemBatch(), 10);
        Test.stopTest();
    }

    @isTest
    static void testBatchWithMultipleReceipts() {

        Booking__c booking = new Booking__c();
        insert booking;

        Payment_Schedule__c ps = new Payment_Schedule__c();
        ps.Booking__c          = booking.Id;
        ps.S_No__c             = 1;
        insert ps;

        Date baseDate = Date.newInstance(2024, 1, 1);
        List<Receipt__c> receipts = new List<Receipt__c>();
        for (Integer i = 0; i < 3; i++) {
            Receipt__c rc             = new Receipt__c();
            rc.Booking__c             = booking.Id;
            rc.Manual_Upload__c       = true;
            rc.Receipt_Date__c        = baseDate.addDays(i);
            rc.Amount_Received__c     = 10000;
            rc.Mode_Of_Payment__c     = 'Cheque';
            rc.Check_Transaction_Nmber__c = 'TXN00' + i;
            rc.Cheque_Date__c         = baseDate.addDays(i);
            receipts.add(rc);
        }
        insert receipts;

        Test.startTest();
        Database.executeBatch(new ReceiptLineItemBatch(), 10);
        Test.stopTest();
    }

    @isTest
    static void testBatchNoReceipts() {

        Booking__c booking = new Booking__c();
        insert booking;

        Payment_Schedule__c ps = new Payment_Schedule__c();
        ps.Booking__c          = booking.Id;
        ps.S_No__c             = 1;
        insert ps;

        Test.startTest();
        Database.executeBatch(new ReceiptLineItemBatch(), 10);
        Test.stopTest();
    }

    @isTest
    static void testBatchNoSchedules() {

        Booking__c booking = new Booking__c();
        insert booking;

        Receipt__c rc             = new Receipt__c();
        rc.Booking__c             = booking.Id;
        rc.Manual_Upload__c       = true;
        rc.Receipt_Date__c        = Date.newInstance(2024, 1, 1);
        rc.Amount_Received__c     = 10000;
        rc.Mode_Of_Payment__c     = 'Cheque';
        insert rc;

        Test.startTest();
        Database.executeBatch(new ReceiptLineItemBatch(), 10);
        Test.stopTest();
    }

    @isTest
    static void testBatchMultipleBookings() {

        List<Booking__c> bookings = new List<Booking__c>{
            new Booking__c(),
            new Booking__c()
        };
        insert bookings;

        List<Payment_Schedule__c> schedules = new List<Payment_Schedule__c>{
            new Payment_Schedule__c(Booking__c = bookings[0].Id, S_No__c = 1),
            new Payment_Schedule__c(Booking__c = bookings[1].Id, S_No__c = 1)
        };
        insert schedules;

        List<Receipt__c> receipts = new List<Receipt__c>{
            new Receipt__c(Booking__c = bookings[0].Id, Manual_Upload__c = true,
                           Receipt_Date__c = Date.newInstance(2024, 1, 1),
                           Amount_Received__c = 20000, Mode_Of_Payment__c = 'NEFT'),
            new Receipt__c(Booking__c = bookings[1].Id, Manual_Upload__c = true,
                           Receipt_Date__c = Date.newInstance(2024, 1, 1),
                           Amount_Received__c = 30000, Mode_Of_Payment__c = 'NEFT')
        };
        insert receipts;

        Test.startTest();
        Database.executeBatch(new ReceiptLineItemBatch(), 10);
        Test.stopTest();
    }
}